### ISSUE TITLE
.deb file needs update

### ISSUE THREAD

**Issue by mstrobl2** [patjak/mba6x_bl#15]
Looks like the deb file linked on the project page is not current. I tried it on my MacBook Air with Linux Mint 17 and it did not work well. It would only reset the screen brightness if I had it set to at least 90%  which is way too bright for normal use. Anything less and the screen was black on resume.

I downloaded the master branch and made a DKMS module and it works well (thanks!).

A new deb package with the latest code would be good.

**Comment by hawodi** [comment]
On Ubuntu 15.10  I get the following errors: 
`/var/lib/dkms/mba6xbl/0.0.3/build/mba6x_bl.c: In function ‘platform_probe’:
/var/lib/dkms/mba6xbl/0.0.3/build/mba6x_bl.c:297:2: error: implicit declaration of function ‘acpi_video_dmi_promote_vendor’ [-Werror=implicit-function-declaration]
  acpi_video_dmi_promote_vendor();
  ^
cc1: some warnings being treated as errors
scripts/Makefile.build:264: recipe for target '/var/lib/dkms/mba6xbl/0.0.3/build/mba6x_bl.o' failed
make[2]: *** [/var/lib/dkms/mba6xbl/0.0.3/build/mba6x_bl.o] Error 1
Makefile:1398: recipe for target '_module_/var/lib/dkms/mba6xbl/0.0.3/build' failed
make[1]: *** [_module_/var/lib/dkms/mba6xbl/0.0.3/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.2.0-27-generic'
Makefile:8: recipe for target 'all' failed
make: *** [all] Error 2`
