### ISSUE TITLE
is there a way to change the starting brightness?

### ISSUE THREAD

**Issue by eugenecormier** [patjak/mba6x_bl#23]
I load a script on boot that sets the brightness to 255, but there is time from when the module gets loaded until my script is run that it looks like it's about 80% brightness, is there somewhere in your source that I can change that setting to 100% before compile?

**Comment by patjak** [comment]
Hi, you can change the start brightness by modifying INIT_BRIGHTNESS in mba6x_bl.c. The default value is 150 (~60%). It is currently set to an arbitrary value so that I can see at what point during boot mba6x_bl kicks in.

**Comment by eugenecormier** [comment]
thanks patjak

**Comment by eugenecormier** [comment]
Just tried it, worked perfectly, thanks so much for your work on this.... there is still some weirdness with the driver.... now brightness works across suspend, but I still loose FB decorations after suspend.... not sure if it has anything to do with your module, but that's what I'm seeing (and have always seen aka: before your module)
