### ISSUE TITLE
Starting Mac in Ubuntu after shut down from Ubuntu=No problem. Starting Mac in Ubuntu after shutdown from OSX=Black Screen

### ISSUE THREAD

**Issue by hpe009** [patjak/mba6x_bl#24]
I am using refind boot-menu, when I start up the computer after shutting down from ubuntu there is no problem after starting up in Ubuntu. But when i start up the computer after I have been in OS X, I get a black screen when the Mac is started up in Ubuntu. I have the mba6x_bl kernel module installed. this is what happen with me. Please help, @patjak

**Comment by patjak** [comment]
I have the same problem but instead of a black screen I get the i915 default backlight functionality. I'm currently relocating and starting a new job but as soon as things calm down I'll look into it.

**Comment by hpe009** [comment]
@patjak I know that this is of topic, but do you know how to make refind not show vmlinuz-kernelversion. And only show the grub bootloader as an option?

**Comment by patjak** [comment]
After a firmware upgrade I couldn't run refind anymore so I put grub directly on the EFI partition and blessed it. Now I boot straight into Linux and if I need OSX I just hold down "option" which gives me the built-in boot menu. Hope that helps

**Comment by hpe009** [comment]
I am a noob with that sort of thing, so you could not help me do that? @patjak

**Comment by eugenecormier** [comment]
@hpe009 that is way off topic.... uninstall refind and using a ubuntu livecd (with efi) reinstall the bootloader... google is your friend

**Comment by patjak** [comment]
Yes it's a bit off topic and to be honest I don't really remember what I did. I found a "note to self" post on G+ where I explained how to get Refind working after the SMC upgrade. I guess you can do the same but replace Refind with Grub and things should work. Here's what I did: https://plus.google.com/+PatrikJakobsson/posts/GvyJz21XsCM

**Comment by hpe009** [comment]
Closing as I can not reproduce the problem anymore, and it may had something to do with Linux/Ubuntu
