### ISSUE TITLE
Enhance functionalty

### ISSUE THREAD

**Issue by 5hubh4m** [patjak/mba6x_bl#30]
I'm new to kernel programming and I'm looking to emulate a similar feature to OS X. I want the brightness to go gradually from the set value to zero when the lid is closed. How do I detect that the system is suspended. I was looking at platform_shutdown function. I was hoping you could guide me on this...

**Comment by 5hubh4m** [comment]
Resolved it by adding the .suspend callback method in platform_device struct and instruct it to take back light to zero gradually.

**Comment by andrewgaul** [comment]
#31.
