### ISSUE TITLE
Screen dims and lights repeatly when lip is closed

### ISSUE THREAD

**Issue by sunqingyao** [patjak/mba6x_bl#38]
I've installed this module on my macbook air early 2015 runing Fedora 22, and it does works for the first few days. But there is a problem now: When I close the lip, the screen will dim for about 15 seconds, then it will light up automatically. 15 seconds later, it will dim for another 15 seconds, and light up magically again.

**Comment by patjak** [comment]
Have you tried
`` echo XHC1 > /proc/acpi/wakeup ``
