### ISSUE TITLE
module no longer works with 4.2.0-18-generic #22-Ubuntu SMP

### ISSUE THREAD

**Issue by thekswenson** [patjak/mba6x_bl#40]
Thanks for the module...
  I've been using it for a year a so.  It's integral to the enjoyment of my laptop.

Recently I've updated the kernel a few times and just noticed that the module doesn't seem to be working anymore.
After doing "sudo make install" and "sudo depmod -a" and "sudo modprobe mba6x_bl" and rebooting I see that the module is loaded:
"""
=> lsmod | grep mba
mba6x_bl               16384  0
video                  36864  2 i915,mba6x_bl
"""

Is it possible I'm doing something wrong?

**Comment by patjak** [comment]
Hi, can you describe the problem? Is it still possible to change the backlight or is it just stuck at some level?

**Comment by thekswenson** [comment]
Loading the module doesn't change anything.  After suspend, the brightness
can be all or nothing only, as if I hadn't loaded the module.

**Comment by patjak** [comment]
Do you have a /sys/class/backlight/mba6x_bl directory when the module is loaded?

**Comment by patjak** [comment]
Oh, and could you attach a full dmesg when mba6x_bl is being loaded?

**Comment by thekswenson** [comment]
There is no /sys/class/backlight/mba6x_bl.
=> ls /sys/class/backlight/
acpi_video0@  intel_backlight@

**Comment by thekswenson** [comment]
[  200.936799] mba6x_bl: Found LP8550 backlight driver

**Comment by thekswenson** [comment]
I don't understand what is going on now but the process of loading and unloading (with modprobe, nothing else) the module has changed everything...
    things seem to be working normally for now!?

Also the contents of /sys/class/backlight/ have changed:
=> ls /sys/class/backlight/
intel_backlight@  mba6x_backlight@

**Comment by patjak** [comment]
That's odd. Lets just pretend we fixed it and that nobody else runs into this :)

Reopen if the problem comes back.

**Comment by proninyaroslav** [comment]
I have the same problem (4.2.0-19-generic). After the release of the suspend -  black screen.
