### ISSUE TITLE
initial 'make' error

### ISSUE THREAD

**Issue by itpun** [patjak/mba6x_bl#48]
causes this issue:

make -C /lib/modules/4.2.3-300.fc23.x86_64/build M=/home/ipun/git/mba6x_bl modules
make[1]: *** /lib/modules/4.2.3-300.fc23.x86_64/build: No such file or directory.  Stop.

any ideas? i checked inside that folder hosting the build file and it exists. It has a @ at the end of it (build@).

**Comment by agimenez** [comment]
Maybe you are missing your distro's "linux headers" package?

**Comment by patjak** [comment]
Closing this since it's not mba6x_bl specific. Check distro docs on how to install kernel modules in Fedora.
